### ISSUE TITLE
Does not work with current Flutter version (not compatible with Dart2)

### ISSUE THREAD

**Issue by fvisticot** [hitherejoe/FlutterOAuth#12]
[VERBOSE-2:dart_error.cc(16)] Unhandled exception:
type 'Future<dynamic>' is not a subtype of type 'Future<Null>'
#0      FlutterWebviewPlugin.close (package:flutter_webview_plugin/flutter_webview_plugin.dart:73:36)
#1      FlutterOAuth.requestCode (package:flutter_oauth/lib/flutter_auth.dart:26:21)
<asynchronous suspension>
#2      OAuth.performAuthorization (package:flutter_oauth/lib/oauth.dart:49:31)

**Comment by simonbohnen** [comment]
Seems to be the same as #8.

**Comment by hitherejoe** [comment]
Update coming out over the weekend :)

**Comment by simonbohnen** [comment]
When is the update coming?
