### ISSUE TITLE
Need to upgrade flutter webview plugin dependency

### ISSUE THREAD

**Issue by matthew-carroll** [hitherejoe/FlutterOAuth#8]
I'm getting errors related to a return type of Future<Null> within the flutter_webview_plugin.  I checked that repo and those response types have been changed to a generic Future without the <Null>.  I think you need to update the dependency number to get the latest flutter_webview_plugin.

**Comment by manuelgomes2** [comment]
This doesn't work with Flutter beta 2 / Dart2 because of this dependency

**Comment by manuelgomes2** [comment]
It still works in Flutter beta 2, but only if Dart 2 support is disabled...

**Comment by richmidwinter** [comment]
I'm getting this too. 👎

**Comment by tristanwilson111** [comment]
+1. The webview doesn't appear and throws the Future error described above. @hitherejoe

**Comment by simonbohnen** [comment]
Still doesn't seem to be fixed, could anyone tell me how I work around this myself? I'm a little stuck to be honest.

**Comment by hitherejoe** [comment]
Sorry for the delay, merged this in and will get an update out over the weekend :)
